import { StyleSheet } from 'react-native';
import { colors } from '@theme/colors';
import { ms, s, vs } from 'react-native-size-matters/extend';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: colors.white,
    paddingHorizontal: s(16),
  },
  containerStyle: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraParent: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  // scannerWrapper: {
  //   width: s(300),
  //   height: vs(300),
  //   borderRadius: 8,
  //   overflow: 'hidden',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   backgroundColor: colors.white,
  //   alignSelf: 'center',
  //   padding: vs(16),
  // },
  // cameraView: {
  //   width: '100%',
  //   height: '100%',
  //   borderRadius: 8,
  // },
  scannerWrapper: {
    flex: 1,
    width: '100%',
    aspectRatio: 1, // or 3/4 for a rectangle
    maxWidth: s(300),
    maxHeight: vs(300),
    borderRadius: 12,
    // overflow: 'hidden',
    backgroundColor: colors.black,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  cameraView: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 12,
  },
  noPermissionContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  permissionBtn: {
    backgroundColor: colors.buttonBg,
    borderRadius: ms(6),
    paddingVertical: vs(10),
    paddingHorizontal: s(10),
    marginTop: vs(5),
  },
  scanAgainBtn: {
    backgroundColor: colors.buttonBg,
    borderRadius: ms(6),
    paddingVertical: vs(10),
    paddingHorizontal: s(10),
    alignSelf: 'center',
    marginTop: vs(20),
  },
  scanAgainText: {
    textAlign: 'center',
    color: colors.white,
  },
  overlayCornerTL: {
    position: 'absolute',
    top: -15,
    left: -15,
    width: s(20),
    height: vs(20),
    borderTopWidth: s(3),
    borderLeftWidth: s(3),
    borderColor: colors.black,
    zIndex: 1111,
  },
  overlayCornerTR: {
    position: 'absolute',
    top: -15,
    right: -15,
    width: s(20),
    height: vs(20),
    borderTopWidth: s(3),
    borderRightWidth: s(3),
    borderColor: colors.black,
  },
  overlayCornerBL: {
    position: 'absolute',
    bottom: -15,
    left: -15,
    width: s(20),
    height: vs(20),
    borderBottomWidth: s(3),
    borderLeftWidth: s(3),
    borderColor: colors.black,
  },
  overlayCornerBR: {
    position: 'absolute',
    bottom: -15,
    right: -15,
    width: s(20),
    height: vs(20),
    borderBottomWidth: s(3),
    borderRightWidth: s(3),
    borderColor: colors.black,
  },
});
export default styles;
