export const getStartBg1 = require('@assets/images/getStartBg1.png');
export const getStartBg2 = require('@assets/images/getStartBg2.png');
export const getStartBg3 = require('@assets/images/getStartBg3.png');
export const getStartBg4 = require('@assets/images/getStartBg4.png');
export const backIcon = require('@assets/images/backIcon.png');
export const eyeOpenIcon = require('@assets/images/eyeOpenIcon.png');
export const eyeCloseIcon = require('@assets/images/eyeCloseIcon.png');
export const emailIcon = require('@assets/images/emailIcon.png');
export const authBg = require('@assets/images/authBg.png');
export const userIcon = require('@assets/images/userIcon.png');
export const phoneIcon = require('@assets/images/phoneIcon.png');
export const homeIcon = require('@assets/images/homeIcon.png');
export const helpLineIcon = require('@assets/images/helpLineIcon.png');
export const nearByIcon = require('@assets/images/nearByIcon.png');
export const proflieIcon = require('@assets/images/profileIcon.png');
export const locationIcon = require('@assets/images/locationIcon.png');
export const downArrowIcon = require("@assets/images/downIcon.png");
export const searchIcon =require("@assets/images/searchIcon.png")
